{% set version = "0.2.1" %}
{% set sha256 = "b27b1b2e1b6726096c8e91728c6bd7ee8c007b09fd8f94f0157ce7ca1975d72e" %}

package:
  name: vcfkit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/V/VCF-kit/VCF-kit-{{ version }}.tar.gz
  sha256: b27b1b2e1b6726096c8e91728c6bd7ee8c007b09fd8f94f0157ce7ca1975d72e
  patches:
    - setup.patch
    # Fixes https://github.com/AndersenLab/VCF-kit/issues/22
    - numpy.patch

build:
  number: 0
  noarch: python
  entry_points:
    - vk=vcfkit.vk:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python <3
  run:
    - awesome-slugify
    - biopython
    - clint
    - cyvcf2 >=0.6.5
    - docopt
    - intervaltree ==2.1.0
    - jinja2
    - matplotlib
    - networkx ==1.11
    - numpy
    - python <3
    - requests
    - scipy
    - tabulate
    - yahmm >=1.1.2
    - bwa >=0.7.12
    - samtools >=1.3
    - bcftools >=1.3
    - blast >=2.2.31
    - muscle >=3.8.31

test:
  imports:
    - vcfkit
    - vcfkit.utils
  commands:
    - vk --help

about:
  home: https://github.com/AndersenLab/VCF-kit
  license: MIT
  license_family: MIT
  summary: "VCF-kit is a command-line based collection of utilities for performing analysis on Variant Call Format (VCF) files."
